services:
  # 1. Your FastAPI Application
  api:
    build: .
    container_name: fintech_api
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy # FORCES THE API TO WAIT FOR THE DB TO BE FULLY READY
      redis:
        condition: service_started # <--- ADDED: FORCES API TO WAIT FOR REDIS
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - REDIS_URL=redis://redis:6379/0 # <--- ADDED: THE INTERNAL NETWORK URL FOR REDIS
    volumes:
      - ./:/app # Maps local directory to container root
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --reload-exclude '.venv/*'
    networks:
      - fintech_network

  # 2. Your PostgreSQL Storage Engine
  db:
    image: postgres:15-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d market_data"]
      interval: 5s
      timeout: 5s
      retries: 5
    container_name: fintech_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fintech_network

  # 3. Your Redis Central Cache (Day 25 Addition)
  redis:
    image: redis:7-alpine
    container_name: fintech_redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - fintech_network # <--- Crucial: Maps Redis to the same internal bridge network

# 4. Persistent Storage
volumes:
  postgres_data:

# 5. Isolated Networking
networks:
  fintech_network:
    driver: bridge