from pydantic import BaseModel, Field
from typing import Optional



class IntelligenceResponse(BaseModel):
    ticker: str = Field(..., description="The target asset symbol (e.g., AAPL)")
    signal: str = Field(..., description="The final alpha signal: BUY, SELL, HOLD, or INVALID")
    analysis_report: str = Field(..., description="The structured reasoning generated by the AI agent")
    execution_time_ms: float = Field(..., description="Latency tracking for observability and SLA monitoring")




class JobAcceptedResponse(BaseModel):
    job_id: str = Field(..., description="Unique UUID for tracking the background task")
    status: str = Field(default="processing", description="Current state of the engine")
    message: str = Field(default="Task offloaded to background worker.")

class JobStatusResponse(BaseModel):
    job_id: str
    status: str = Field(..., description="'processing', 'completed', or 'failed'")
    result: Optional[IntelligenceResponse] = Field(default=None, description="The final payload if completed")