from typing import Optional
from pydantic import BaseModel, Field, field_validator

class MarketDataPayload(BaseModel):
    """
    Data transfer contract and edge firewall schema for raw market data payloads.
    Enforces strict structural validation before database persistence or queue dispatch.
    """
    ticker: str = Field(..., description="Equity ticker symbol (e.g., AAPL, TSLA)")
    asset_class: str = Field(..., description="Asset type classification")
    current_price: float = Field(..., gt=0.0, description="Current spot price, must be strictly positive")
    volume: int = Field(..., gt=0, description="24-hour trading volume")

    @field_validator("ticker")
    @classmethod
    def validate_ticker_format(cls, value: str) -> str:
        """Sanitize and validate equity ticker symbol format."""
        clean_ticker = value.upper().strip()
        if not clean_ticker.isalpha() or not (1 <= len(clean_ticker) <= 5):
            raise ValueError("Ticker must be 1-5 alphabetic characters only.")
        return clean_ticker
    
    @field_validator("asset_class")
    @classmethod
    def validate_class_method(cls, value: str) -> str:
        """Ensure asset class falls within permitted financial domains."""
        allowed = {"CRYPTO", "FOREX", "EQUITY", "COMMODITY"}
        clean_value = value.upper().strip()
        if clean_value not in allowed:
            raise ValueError(f"Asset class must be one of {allowed}")
        return clean_value

    

# Core output schema for intelligence analysis results
class IntelligenceResponse(BaseModel):
    """
    Core output schema for multi-agent intelligence analysis results.
    Defines the immutable JSON contract served by the CQRS query edge.
    """
    ticker: str = Field(..., description="The target asset symbol (e.g., AAPL)")
    signal: str = Field(..., description="The final alpha signal: BUY, SELL, HOLD, or INVALID")
    analysis_report: str = Field(..., description="The structured reasoning generated by the AI agent")
    execution_time_ms: float = Field(..., description="Latency tracking for observability and SLA monitoring")


# Response schema for accepted background tasks
class JobAcceptedResponse(BaseModel):
    """
    Response schema returned immediately upon asynchronous job registration (HTTP 202).
    """
    job_id: str = Field(..., description="Unique UUID for tracking the background task")
    status: str = Field(default="processing", description="Current state of the engine")
    message: str = Field(default="Task offloaded to background worker.")


# Response schema for polling the status of asynchronous jobs
class JobStatusResponse(BaseModel):
    """
    Response schema for polling the runtime state of asynchronous intelligence tasks from Redis.
    """
    job_id: str
    status: str = Field(..., description="'processing', 'completed', or 'failed'")
    result: Optional[IntelligenceResponse] = Field(default=None, description="The final payload if completed")


# ==================================================
# MULTI-ASSET BATCH ORCHESTRATION SCHEMAS
# ==================================================

class BatchAnalysisRequest(BaseModel):
    """
    Zero-Trust Pydantic Perimeter for multi-asset batch dispatch.
    Limits batch size to 50 tickers, sanitizes inputs, deduplicates symbols,
    and filters out malformed items with high-availability resilience.
    """
    tickers: list[str] = Field(
        ...,
        min_length=1,
        max_length=50,
        description="List of 1-50 US equity ticker symbols to analyze simultaneously"
    )

    @field_validator("tickers")
    @classmethod
    def sanitize_and_filter_tickers(cls, values: list[str]) -> list[str]:
        valid_tickers: list[str] = []
        seen: set[str] = set()

        for raw in values:
            if not isinstance(raw, str):
                continue
            clean = raw.upper().strip()
            # Enforce strict 1-5 alphabetic character boundary
            if clean.isalpha() and (1 <= len(clean) <= 5):
                if clean not in seen:
                    seen.add(clean)
                    valid_tickers.append(clean)

        if not valid_tickers:
            raise ValueError("Batch request must contain at least one valid 1-5 character alphabetic ticker.")

        return valid_tickers


class BatchJobItem(BaseModel):
    """Individual asset tracking unit inside a distributed batch dispatch."""
    ticker: str = Field(..., description="Target equity ticker symbol")
    job_id: str = Field(..., description="Unique UUID for real-time WebSocket stream binding")


class BatchJobAcceptedResponse(BaseModel):
    """HTTP 202 Response schema returned immediately upon batch task acceptance."""
    batch_id: str = Field(..., description="Parent batch identifier for multi-asset tracking")
    total_assets: int = Field(..., description="Total sanitized assets queued for analysis")
    status: str = Field(default="queued", description="Initial queue state")
    jobs: list[BatchJobItem] = Field(..., description="Asset-to-Job mapping for real-time telemetry")
    message: str = Field(default="Multi-asset batch accepted and dispatched to async worker fan-out.")


# ==================================================
# LIVE JOB AUDIT REGISTRY CONTRACTS
# ==================================================

class JobAuditEntry(BaseModel):
    """
    Snapshot of a single active or recently completed intelligence job.
    Reconstructed from a Redis SCAN — requires zero PostgreSQL queries.
    Age is estimated from the job's remaining TTL against the fixed 3600s expiry.
    """
    job_id: str = Field(..., description="UUID tracking token for this job")
    ticker: str = Field(..., description="Target equity ticker symbol")
    status: str = Field(..., description="'processing' | 'completed' | 'failed'")
    batch_id: Optional[str] = Field(default=None, description="Parent batch ID if dispatched via batch endpoint")
    age_seconds: int = Field(..., description="Estimated seconds since job was dispatched (3600 - TTL)")
    signal: Optional[str] = Field(default=None, description="BUY/SELL/HOLD/INVALID — populated on completion only")
    execution_time_ms: Optional[float] = Field(default=None, description="Agent execution latency — populated on completion only")


class SystemAuditResponse(BaseModel):
    """
    Aggregated live job registry payload returned by GET /v1/intelligence/audit.
    Provides an instant operational snapshot of all active Redis job states
    with summary counters for dashboard consumption.
    """
    total_active_jobs: int = Field(..., description="Total jobs present in Redis at time of scan")
    processing: int = Field(..., description="Jobs currently executing in background workers")
    completed: int = Field(..., description="Jobs that have finished and cached their result")
    failed: int = Field(..., description="Jobs that crashed with an exception")
    jobs: list[JobAuditEntry] = Field(..., description="Individual job snapshots, sorted processing-first")
    audit_timestamp_ms: int = Field(..., description="Unix epoch milliseconds when the scan was performed")


# ==================================================
# DEAD-LETTER QUEUE (DLQ) AUDIT CONTRACTS
# ==================================================

class DeadLetterJobEntry(BaseModel):
    """
    Diagnostic schema for a quarantined Dead-Letter Queue (DLQ) entry.
    """
    dlq_id: str = Field(..., description="Monotonic stream entry ID in the DLQ")
    original_message_id: str = Field(..., description="Original stream ID before quarantine")
    job_id: str = Field(..., description="UUID tracking token")
    ticker: str = Field(..., description="Target equity symbol")
    batch_id: Optional[str] = Field(default=None, description="Parent batch ID if applicable")
    trace_id: Optional[str] = Field(default=None, description="Telemetry trace correlation ID")
    delivery_count: int = Field(..., description="Total failed delivery attempts before quarantine")
    error_reason: str = Field(..., description="Root cause diagnostics")
    quarantined_at: float = Field(..., description="Unix timestamp when message was quarantined")


class DeadLetterRegistryResponse(BaseModel):
    """
    Aggregated response payload for GET /v1/intelligence/dlq.
    """
    total_quarantined: int = Field(..., description="Total messages currently in the DLQ")
    entries: list[DeadLetterJobEntry] = Field(..., description="List of quarantined jobs")
    audit_timestamp_ms: int = Field(..., description="Timestamp of the query")
