from typing import Optional
from pydantic import BaseModel, Field, field_validator

class MarketDataPayload(BaseModel):
    """
    Data transfer contract and edge firewall schema for raw market data payloads.
    Enforces strict structural validation before database persistence or queue dispatch.
    """
    ticker: str = Field(..., description="Equity ticker symbol (e.g., AAPL, TSLA)")
    asset_class: str = Field(..., description="Asset type classification")
    current_price: float = Field(..., gt=0.0, description="Current spot price, must be strictly positive")
    volume: int = Field(..., gt=0, description="24-hour trading volume")

    @field_validator("ticker")
    @classmethod
    def validate_ticker_format(cls, value: str) -> str:
        """Sanitize and validate equity ticker symbol format."""
        clean_ticker = value.upper().strip()
        if not clean_ticker.isalpha() or not (1 <= len(clean_ticker) <= 5):
            raise ValueError("Ticker must be 1-5 alphabetic characters only.")
        return clean_ticker
    
    @field_validator("asset_class")
    @classmethod
    def validate_class_method(cls, value: str) -> str:
        """Ensure asset class falls within permitted financial domains."""
        allowed = {"CRYPTO", "FOREX", "EQUITY", "COMMODITY"}
        clean_value = value.upper().strip()
        if clean_value not in allowed:
            raise ValueError(f"Asset class must be one of {allowed}")
        return clean_value

    

# Core output schema for intelligence analysis results
class IntelligenceResponse(BaseModel):
    """
    Core output schema for multi-agent intelligence analysis results.
    Defines the immutable JSON contract served by the CQRS query edge.
    """
    ticker: str = Field(..., description="The target asset symbol (e.g., AAPL)")
    signal: str = Field(..., description="The final alpha signal: BUY, SELL, HOLD, or INVALID")
    analysis_report: str = Field(..., description="The structured reasoning generated by the AI agent")
    execution_time_ms: float = Field(..., description="Latency tracking for observability and SLA monitoring")


# Response schema for accepted background tasks
class JobAcceptedResponse(BaseModel):
    """
    Response schema returned immediately upon asynchronous job registration (HTTP 202).
    """
    job_id: str = Field(..., description="Unique UUID for tracking the background task")
    status: str = Field(default="processing", description="Current state of the engine")
    message: str = Field(default="Task offloaded to background worker.")


# Response schema for polling the status of asynchronous jobs
class JobStatusResponse(BaseModel):
    """
    Response schema for polling the runtime state of asynchronous intelligence tasks from Redis.
    """
    job_id: str
    status: str = Field(..., description="'processing', 'completed', or 'failed'")
    result: Optional[IntelligenceResponse] = Field(default=None, description="The final payload if completed")