from typing import Optional, Dict, Any
from pydantic import BaseModel, Field, field_validator


class MarketDataPayload(BaseModel):
    """
    Data transfer contract and edge firewall schema for raw market data payloads.
    Enforces strict structural validation before database persistence or queue dispatch.
    """

    ticker: str = Field(..., description="Equity ticker symbol (e.g., AAPL, TSLA)")
    asset_class: str = Field(..., description="Asset type classification")
    current_price: float = Field(..., gt=0.0, description="Current spot price, must be strictly positive")
    volume: int = Field(..., gt=0, description="24-hour trading volume")

    @field_validator("ticker")
    @classmethod
    def validate_ticker_format(cls, value: str) -> str:
        """Sanitize and validate equity ticker symbol format."""
        clean_ticker = value.upper().strip()
        if not clean_ticker.isalpha() or not (1 <= len(clean_ticker) <= 5):
            raise ValueError("Ticker must be 1-5 alphabetic characters only.")
        return clean_ticker

    @field_validator("asset_class")
    @classmethod
    def validate_class_method(cls, value: str) -> str:
        """Ensure asset class falls within permitted financial domains."""
        allowed = {"CRYPTO", "FOREX", "EQUITY", "COMMODITY"}
        clean_value = value.upper().strip()
        if clean_value not in allowed:
            raise ValueError(f"Asset class must be one of {allowed}")
        return clean_value


# Core output schema for intelligence analysis results
class IntelligenceResponse(BaseModel):
    """
    Core output schema for multi-agent intelligence analysis results.
    Defines the immutable JSON contract served by the CQRS query edge.
    """

    ticker: str = Field(..., description="The target asset symbol (e.g., AAPL)")
    signal: str = Field(..., description="The final alpha signal: BUY, SELL, HOLD, or INVALID")
    analysis_report: str = Field(..., description="The structured reasoning generated by the AI agent")
    execution_time_ms: float = Field(..., description="Latency tracking for observability and SLA monitoring")


# Response schema for accepted background tasks
class JobAcceptedResponse(BaseModel):
    """
    Response schema returned immediately upon asynchronous job registration (HTTP 202).
    """

    job_id: str = Field(..., description="Unique UUID for tracking the background task")
    status: str = Field(default="processing", description="Current state of the engine")
    message: str = Field(default="Task offloaded to background worker.")
    trace_id: Optional[str] = Field(default=None, description="Distributed W3C trace identifier")


# Response schema for polling the status of asynchronous jobs
class JobStatusResponse(BaseModel):
    """
    Response schema for polling the runtime state of asynchronous intelligence tasks from Redis.
    """

    job_id: str
    status: str = Field(..., description="'processing', 'completed', or 'failed'")
    result: Optional[IntelligenceResponse] = Field(default=None, description="The final payload if completed")
    error: Optional[str] = Field(default=None, description="Error detail if failed")
    trace_id: Optional[str] = Field(default=None, description="Distributed W3C trace identifier")


# ==================================================
# MULTI-ASSET BATCH ORCHESTRATION SCHEMAS
# ==================================================


class BatchAnalysisRequest(BaseModel):
    """
    Zero-Trust Pydantic Perimeter for multi-asset batch dispatch.
    Limits batch size to 50 tickers, sanitizes inputs, deduplicates symbols,
    and filters out malformed items with high-availability resilience.
    """

    tickers: list[str] = Field(
        ..., min_length=1, max_length=50, description="List of 1-50 US equity ticker symbols to analyze simultaneously"
    )

    @field_validator("tickers")
    @classmethod
    def sanitize_and_filter_tickers(cls, values: list[str]) -> list[str]:
        valid_tickers: list[str] = []
        seen: set[str] = set()

        for raw in values:
            if not isinstance(raw, str):
                continue
            clean = raw.upper().strip()
            # Enforce strict 1-5 alphabetic character boundary
            if clean.isalpha() and (1 <= len(clean) <= 5):
                if clean not in seen:
                    seen.add(clean)
                    valid_tickers.append(clean)

        if not valid_tickers:
            raise ValueError("Batch request must contain at least one valid 1-5 character alphabetic ticker.")

        return valid_tickers


class BatchJobItem(BaseModel):
    """Individual asset tracking unit inside a distributed batch dispatch."""

    ticker: str = Field(..., description="Target equity ticker symbol")
    job_id: str = Field(..., description="Unique UUID for real-time WebSocket stream binding")


class BatchJobAcceptedResponse(BaseModel):
    """HTTP 202 Response schema returned immediately upon batch task acceptance."""

    batch_id: str = Field(..., description="Parent batch identifier for multi-asset tracking")
    total_assets: int = Field(..., description="Total sanitized assets queued for analysis")
    status: str = Field(default="queued", description="Initial queue state")
    jobs: list[BatchJobItem] = Field(..., description="Asset-to-Job mapping for real-time telemetry")
    message: str = Field(default="Multi-asset batch accepted and dispatched to async worker fan-out.")
    trace_id: Optional[str] = Field(default=None, description="Distributed W3C trace identifier")


# ==================================================
# LIVE JOB AUDIT REGISTRY CONTRACTS
# ==================================================


class JobAuditEntry(BaseModel):
    """
    Snapshot of a single active or recently completed intelligence job.
    Reconstructed from a Redis SCAN — requires zero PostgreSQL queries.
    Age is estimated from the job's remaining TTL against the fixed 3600s expiry.
    """

    job_id: str = Field(..., description="UUID tracking token for this job")
    ticker: str = Field(..., description="Target equity ticker symbol")
    status: str = Field(..., description="'processing' | 'completed' | 'failed'")
    batch_id: Optional[str] = Field(default=None, description="Parent batch ID if dispatched via batch endpoint")
    age_seconds: int = Field(..., description="Estimated seconds since job was dispatched (3600 - TTL)")
    signal: Optional[str] = Field(default=None, description="BUY/SELL/HOLD/INVALID — populated on completion only")
    execution_time_ms: Optional[float] = Field(
        default=None, description="Agent execution latency — populated on completion only"
    )
    trace_id: Optional[str] = Field(default=None, description="Distributed W3C trace identifier for correlation")
    cache_primed: bool = Field(
        default=False, description="Whether the intelligence result is primed in write-through/CQRS cache"
    )
    primed_at: Optional[str] = Field(default=None, description="ISO timestamp when result was primed into cache")
    cache_ttl_remaining: Optional[int] = Field(
        default=None, description="Remaining TTL in seconds for the primed cache entry"
    )


class SystemAuditResponse(BaseModel):
    """
    Aggregated live job registry payload returned by GET /v1/intelligence/audit.
    Provides an instant operational snapshot of all active Redis job states
    with summary counters for dashboard consumption.
    """

    total_active_jobs: int = Field(..., description="Total jobs present in Redis at time of scan")
    processing: int = Field(..., description="Jobs currently executing in background workers")
    completed: int = Field(..., description="Jobs that have finished and cached their result")
    failed: int = Field(..., description="Jobs that crashed with an exception")
    jobs: list[JobAuditEntry] = Field(..., description="Individual job snapshots, sorted processing-first")
    audit_timestamp_ms: int = Field(..., description="Unix epoch milliseconds when the scan was performed")


# ==================================================
# DEAD-LETTER QUEUE (DLQ) AUDIT CONTRACTS
# ==================================================


class DeadLetterJobEntry(BaseModel):
    """
    Diagnostic schema for a quarantined Dead-Letter Queue (DLQ) entry.
    """

    dlq_id: str = Field(..., description="Monotonic stream entry ID in the DLQ")
    original_message_id: str = Field(..., description="Original stream ID before quarantine")
    job_id: str = Field(..., description="UUID tracking token")
    ticker: str = Field(..., description="Target equity symbol")
    batch_id: Optional[str] = Field(default=None, description="Parent batch ID if applicable")
    trace_id: Optional[str] = Field(default=None, description="Telemetry trace correlation ID")
    delivery_count: int = Field(..., description="Total failed delivery attempts before quarantine")
    error_reason: str = Field(..., description="Root cause diagnostics")
    quarantined_at: float = Field(..., description="Unix timestamp when message was quarantined")


class DeadLetterRegistryResponse(BaseModel):
    """
    Aggregated response payload for GET /v1/intelligence/dlq.
    """

    total_quarantined: int = Field(..., description="Total messages currently in the DLQ")
    entries: list[DeadLetterJobEntry] = Field(..., description="List of quarantined jobs")
    audit_timestamp_ms: int = Field(..., description="Timestamp of the query")


# ==================================================
# DISTRIBUTED TRACE OBSERVABILITY CONTRACTS
# ==================================================


class TraceSpanEntry(BaseModel):
    """Represents an individual stage span within the distributed processing waterfall."""

    stage: str = Field(
        ...,
        description="Lifecycle stage: INGEST_AND_STREAM_ENQUEUE | STREAM_QUEUE_WAIT | WORKER_MULTI_AGENT_EXECUTION | BROADCAST_AND_PERSIST",
    )
    span_id: Optional[str] = Field(default=None, description="Span identifier")
    duration_ms: Optional[float] = Field(default=None, description="Stage latency in milliseconds")
    status: str = Field(default="COMPLETED", description="Stage execution status: COMPLETED | FAILED | QUARANTINED")


class TraceWaterfallResponse(BaseModel):
    """
    End-to-end distributed trace waterfall for a single transaction lifecycle.
    """

    trace_id: str = Field(..., description="W3C 32-character hexadecimal trace identifier")
    job_id: str = Field(..., description="Associated job tracking UUID")
    ticker: str = Field(..., description="Target equity ticker symbol")
    status: str = Field(..., description="Final job status: completed | failed | dead_lettered")
    total_journey_ms: float = Field(..., description="End-to-end journey latency from edge ingest to client delivery")
    spans: list[TraceSpanEntry] = Field(
        ..., description="Ordered list of execution spans across microservice boundaries"
    )
    server_timestamp_ms: int = Field(..., description="Server wall-clock timestamp of the trace query")


# ==================================================
# DISTRIBUTED CACHE HEALTH & TELEMETRY CONTRACTS
# ==================================================


class CacheHealthResponse(BaseModel):
    """
    Real-time operational health and memory efficiency metrics for the distributed cache.
    """

    hit_count: int = Field(..., description="Total cumulative cache hits")
    miss_count: int = Field(..., description="Total cumulative cache misses")
    total_requests: int = Field(..., description="Total cache inquiries processed")
    hit_ratio_pct: float = Field(..., description="Percentage of requests satisfied by in-memory cache")
    contention_count: int = Field(..., description="Total concurrent stampede contention events absorbed by mutex")
    total_cached_keys: int = Field(..., description="Active cache:intel:* keys in Redis")
    memory_used_mb: float = Field(..., description="Current Redis memory footprint in MB")
    memory_peak_mb: float = Field(..., description="Historical peak Redis memory consumption in MB")
    server_timestamp_ms: int = Field(..., description="Unix timestamp of metrics calculation")


# ==================================================
# DISTRIBUTED CACHE INSPECTOR CONTRACTS
# ==================================================


class CacheInspectorResponse(BaseModel):
    """
    Per-ticker granular cache state, TTL progression, and memory inspection.
    """

    ticker: str = Field(..., description="Target equity ticker symbol")
    is_cached: bool = Field(..., description="Whether a hot cache entry currently exists in Redis")
    ttl_remaining_seconds: int = Field(..., description="Remaining seconds before key expiration")
    ttl_total_seconds: int = Field(default=300, description="Baseline maximum TTL duration")
    payload_size_bytes: int = Field(..., description="Memory footprint of the cached payload in bytes")
    prime_origin: Optional[str] = Field(
        default=None, description="Priming source: WRITE_THROUGH | CACHE_ASIDE | MUTEX_WAIT"
    )
    trace_id: Optional[str] = Field(default=None, description="Associated W3C trace ID from pipeline execution")
    primed_at_iso: Optional[str] = Field(default=None, description="ISO timestamp when key was primed in Redis")
    raw_payload_preview: Optional[Dict[str, Any]] = Field(
        default=None, description="Structured preview of cached intelligence data"
    )
    server_timestamp_ms: int = Field(..., description="Server wall-clock timestamp of inspection")


# ==================================================
# DOCUMENT INGESTION & RAG PIPELINE CONTRACTS
# ==================================================


class DocumentChunkItem(BaseModel):
    chunk_id: str = Field(..., description="Unique deterministic identifier for the chunk")
    chunk_index: int = Field(..., description="Sequential position index within the document")
    ticker: str = Field(..., description="Target equity ticker symbol")
    source_file: str = Field(..., description="Original PDF file name")
    doc_type: str = Field(..., description="Filing type: 10-K, 10-Q, 8-K, RESEARCH")
    page_number: int = Field(..., description="Primary page number in source document")
    page_span: list[int] = Field(default_factory=list, description="List of source pages covered by this chunk")
    content: str = Field(..., description="Extracted textual content of the chunk")
    token_count: int = Field(..., description="Calculated token length")
    char_count: int = Field(..., description="Character count")


class DocumentIngestResponse(BaseModel):
    document_id: str = Field(..., description="Unique generated document identifier")
    ticker: str = Field(..., description="Target equity ticker symbol")
    filename: str = Field(..., description="Uploaded document file name")
    doc_type: str = Field(..., description="Classification of filing")
    total_pages: int = Field(..., description="Total pages parsed from the PDF")
    total_chunks: int = Field(..., description="Total sliding-window chunks generated")
    total_tokens: int = Field(..., description="Sum of tokens across all chunks")
    chunks_preview: list[DocumentChunkItem] = Field(..., description="Preview list of the first parsed chunks")
    trace_id: str = Field(..., description="W3C trace context identifier")


class EmbeddingJobResponse(BaseModel):
    document_id: str = Field(..., description="Target document identifier")
    ticker: str = Field(..., description="Target equity symbol")
    chunks_embedded: int = Field(..., description="Count of successfully embedded chunks")
    embedding_dim: int = Field(..., description="Vector dimensions (e.g., 1536)")
    status: str = Field(default="COMPLETED", description="Vectorization pipeline status")
    latency_ms: float = Field(..., description="Time elapsed during vector embedding generation")
    trace_id: str = Field(..., description="Associated W3C trace ID")


class EmbeddingProgressResponse(BaseModel):
    document_id: str = Field(..., description="Target document identifier")
    ticker: str = Field(..., description="Target equity ticker")
    status: str = Field(..., description="Current status: PARSED | EMBEDDING | COMPLETED | FAILED")
    total_chunks: int = Field(..., description="Total chunks in document")
    embedded_chunks: int = Field(..., description="Number of embedded chunks stored in vector database")
    percentage: float = Field(..., description="Completion percentage (0.0 - 100.0)")


class DocumentSearchResultItem(BaseModel):
    chunk_id: str = Field(..., description="Unique chunk primary key")
    document_id: str = Field(..., description="Parent document identifier")
    ticker: str = Field(..., description="Target equity ticker symbol")
    source_file: str = Field(..., description="Source PDF filename")
    doc_type: str = Field(..., description="Document type classification")
    chunk_index: int = Field(..., description="Ordinal index of the chunk")
    page_number: int = Field(..., description="Source page number")
    content: str = Field(..., description="Textual passage content")
    token_count: int = Field(..., description="Token count of chunk")
    vector_similarity: float = Field(..., description="Cosine similarity score (0.0 to 1.0)")
    lexical_overlap: float = Field(..., description="Keyword overlap fraction")
    similarity_score: float = Field(..., description="Hybrid ranking score")


class DocumentSearchResponse(BaseModel):
    ticker: str = Field(..., description="Searched ticker symbol")
    query: str = Field(..., description="Input search query string")
    total_results: int = Field(..., description="Count of returned candidate matches")
    results: list[DocumentSearchResultItem] = Field(..., description="Ranked list of chunk matches")
    trace_id: str = Field(..., description="Distributed W3C trace ID")


# ==================================================
# STRESS TESTING & CHAOS OBSERVABILITY CONTRACTS
# ==================================================


class LoadTestRequest(BaseModel):
    concurrency: int = Field(default=50, ge=1, le=100, description="Concurrent simulated users")
    duration_seconds: int = Field(default=30, ge=1, le=300, description="Test execution duration in seconds")
    target_endpoints: Optional[list[str]] = Field(default=None, description="Optional subset of endpoints to target")


class LoadTestEndpointMetric(BaseModel):
    endpoint: str = Field(..., description="Target URI path")
    method: str = Field(..., description="HTTP Method")
    request_count: int = Field(..., description="Total requests fired")
    success_count: int = Field(..., description="Successful status responses")
    failure_count: int = Field(..., description="Error responses")
    p50_ms: float = Field(..., description="50th percentile latency")
    p90_ms: float = Field(..., description="90th percentile latency")
    p95_ms: float = Field(..., description="95th percentile latency")
    p99_ms: float = Field(..., description="99th percentile latency")
    avg_latency_ms: float = Field(..., description="Average latency in ms")


class LoadTestReport(BaseModel):
    run_id: str = Field(..., description="Unique load test execution identifier")
    status: str = Field(default="COMPLETED", description="Execution status: RUNNING | COMPLETED | FAILED")
    concurrency: int = Field(..., description="Concurrent virtual users")
    duration_seconds: float = Field(..., description="Test duration in seconds")
    total_requests: int = Field(..., description="Total requests processed")
    total_success: int = Field(..., description="Total successful requests")
    total_failures: int = Field(..., description="Total failed requests")
    requests_per_second: float = Field(..., description="Overall requests per second")
    failure_rate_pct: float = Field(..., description="Failure percentage (0.0 - 100.0)")
    latency_p50_ms: float = Field(..., description="Median latency in milliseconds")
    latency_p90_ms: float = Field(..., description="90th percentile latency")
    latency_p95_ms: float = Field(..., description="95th percentile latency")
    latency_p99_ms: float = Field(..., description="99th percentile latency")
    latency_min_ms: float = Field(..., description="Minimum recorded latency")
    latency_max_ms: float = Field(..., description="Maximum recorded latency")
    endpoint_breakdown: list[LoadTestEndpointMetric] = Field(
        default_factory=list, description="Per-endpoint statistics"
    )
    timestamp_iso: str = Field(..., description="Timestamp of execution in ISO format")
    trace_id: str = Field(..., description="W3C trace context identifier")


# ==================================================
# DATABASE CONNECTION POOL TELEMETRY CONTRACTS
# ==================================================


class ConnectionPoolStatus(BaseModel):
    pool_size: int = Field(..., description="Base configured connection pool size")
    max_overflow: int = Field(..., description="Maximum allowed overflow connections")
    total_capacity: int = Field(..., description="Sum of pool size and max overflow")
    checked_in: int = Field(..., description="Currently idle connections in pool")
    checked_out: int = Field(..., description="Currently active connections in use")
    overflow_active: int = Field(..., description="Active overflow connections")
    saturation_pct: float = Field(..., description="Percentage of connection capacity in use")
    is_exhausted: bool = Field(..., description="Whether pool capacity is fully consumed")
    avg_checkout_latency_ms: float = Field(..., description="Observed round-trip ping/checkout latency")
    timestamp_iso: str = Field(..., description="Timestamp of metric capture")
    trace_id: str = Field(..., description="W3C trace context identifier")


class ConnectionPoolStressRequest(BaseModel):
    concurrency: int = Field(default=25, ge=1, le=50, description="Concurrent connections to check out")
    hold_duration_seconds: float = Field(
        default=2.0, ge=0.5, le=10.0, description="Duration to hold checked-out connections"
    )


class ConnectionPoolStressReport(BaseModel):
    run_id: str = Field(..., description="Unique stress run identifier")
    status: str = Field(default="COMPLETED", description="Execution status: COMPLETED | FAILED")
    requested_connections: int = Field(..., description="Requested connection count")
    acquired_connections: int = Field(..., description="Successfully checked-out connections")
    failed_connections: int = Field(..., description="Connections that timed out or errored")
    peak_saturation_pct: float = Field(..., description="Peak observed saturation percentage")
    avg_queue_wait_ms: float = Field(..., description="Average connection acquisition wait time")
    max_queue_wait_ms: float = Field(..., description="Maximum connection acquisition wait time")
    recovery_time_ms: float = Field(..., description="Elapsed milliseconds to return to idle baseline")
    pool_exhausted: bool = Field(..., description="Whether pool reached full saturation")
    timestamp_iso: str = Field(..., description="Timestamp of stress test completion")
    trace_id: str = Field(..., description="W3C trace context identifier")


# ==================================================
# REDIS MEMORY PRESSURE & EVICTION CONTRACTS
# ==================================================


class RedisMemoryStatus(BaseModel):
    used_memory_mb: float = Field(..., description="Current Redis memory consumption in megabytes")
    peak_memory_mb: float = Field(..., description="Peak historical Redis memory footprint in MB")
    allocated_limit_mb: float = Field(..., description="Configured or provisioned maxmemory boundary in MB")
    memory_utilization_pct: float = Field(..., description="Current memory capacity utilization percentage")
    evicted_keys_count: int = Field(..., description="Cumulative count of keys evicted by LRU/LFU policy")
    expired_keys_count: int = Field(..., description="Cumulative count of keys expired by TTL")
    fragmentation_ratio: float = Field(..., description="Redis memory fragmentation ratio")
    total_tracked_keys: int = Field(..., description="Total active keys in database")
    pressure_status: str = Field(..., description="Operational status: HEALTHY | ELEVATED | CRITICAL")
    timestamp_iso: str = Field(..., description="Timestamp of metric capture")
    trace_id: str = Field(..., description="W3C trace context identifier")


class RedisMemoryPressureRequest(BaseModel):
    target_fill_mb: float = Field(default=5.0, ge=0.5, le=50.0, description="Synthetic target memory fill in MB")
    key_count: int = Field(default=200, ge=10, le=2000, description="Quantity of synthetic pressure keys to populate")
    ttl_seconds: int = Field(default=60, ge=1, le=3600, description="TTL duration for pressure keys")


class RedisMemoryPressureReport(BaseModel):
    run_id: str = Field(..., description="Unique memory stress run identifier")
    status: str = Field(default="COMPLETED", description="Execution status: COMPLETED | FAILED")
    keys_generated: int = Field(..., description="Count of synthetic pressure keys injected")
    memory_before_mb: float = Field(..., description="Memory footprint prior to injection")
    memory_peak_mb: float = Field(..., description="Peak memory recorded during injection")
    memory_after_mb: float = Field(..., description="Memory footprint after cleanup/eviction")
    delta_bytes: int = Field(..., description="Net bytes introduced during test")
    eviction_detected: bool = Field(..., description="Whether key eviction occurred")
    graceful_degradation_verified: bool = Field(..., description="Confirmed cache misses safely resolved to database")
    timestamp_iso: str = Field(..., description="Timestamp of execution in ISO format")
    trace_id: str = Field(..., description="W3C trace context identifier")


# ==================================================
# EVENT LOOP LATENCY & STARVATION BENCHMARK CONTRACTS
# ==================================================


class EventLoopStatus(BaseModel):
    current_lag_ms: float = Field(..., description="Current measured event loop scheduling drift in milliseconds")
    avg_lag_ms: float = Field(..., description="Rolling average event loop lag in milliseconds")
    p95_lag_ms: float = Field(..., description="95th percentile event loop lag in milliseconds")
    max_lag_ms: float = Field(..., description="Maximum recorded event loop lag in current window")
    blocking_events_count: int = Field(..., description="Count of detected scheduling delays exceeding threshold")
    is_starved: bool = Field(..., description="Flag indicating if loop drift exceeds starvation threshold (>15ms)")
    sample_count: int = Field(..., description="Number of rolling latency samples collected")
    recent_samples_ms: list[float] = Field(
        default_factory=list, description="Recent rolling lag measurements for visualization"
    )
    status: str = Field(default="HEALTHY", description="Operational status: HEALTHY | ELEVATED | STARVED")
    timestamp_iso: str = Field(..., description="Timestamp of metric capture")
    trace_id: str = Field(..., description="W3C trace context identifier")


class EventLoopLagSimulationRequest(BaseModel):
    block_duration_ms: float = Field(
        default=50.0, ge=5.0, le=500.0, description="Target blocking delay in milliseconds"
    )
    simulation_type: str = Field(default="cpu_burn", description="Simulation mode: cpu_burn | sync_sleep")


class EventLoopLagSimulationReport(BaseModel):
    run_id: str = Field(..., description="Unique event loop stress run identifier")
    status: str = Field(default="COMPLETED", description="Execution status: COMPLETED | FAILED")
    target_block_ms: float = Field(..., description="Targeted blocking duration")
    measured_lag_ms: float = Field(..., description="Actual observed event loop lag during blocking task")
    recovery_time_ms: float = Field(..., description="Milliseconds required to return to sub-5ms scheduling latency")
    detected_by_monitor: bool = Field(..., description="Whether loop monitor flagged this as a blocking event")
    timestamp_iso: str = Field(..., description="Timestamp of stress completion")
    trace_id: str = Field(..., description="W3C trace context identifier")


# ==================================================
# WORKER KILL & XAUTOCLAIM RECOVERY CHAOS CONTRACTS
# ==================================================


class WorkerChaosSimulationRequest(BaseModel):
    orphaned_message_count: int = Field(
        default=1, ge=1, le=10, description="Quantity of messages to leave unacknowledged"
    )
    min_idle_time_ms: int = Field(
        default=200, ge=50, le=5000, description="Minimum idle time before triggering XAUTOCLAIM"
    )
    consumer_dead_name: str = Field(default="worker_chaos_victim", description="Name of terminated worker consumer")
    consumer_recovery_name: str = Field(
        default="worker_chaos_rescuer", description="Name of claiming recovery consumer"
    )


class WorkerChaosRecoveryReport(BaseModel):
    run_id: str = Field(..., description="Unique chaos recovery run identifier")
    status: str = Field(default="COMPLETED", description="Execution status: COMPLETED | FAILED")
    stream_name: str = Field(..., description="Target Redis stream identifier")
    group_name: str = Field(..., description="Consumer group name")
    orphaned_message_ids: list[str] = Field(default_factory=list, description="IDs of messages orphaned by dead worker")
    claimed_message_ids: list[str] = Field(
        default_factory=list, description="IDs of messages successfully reclaimed via XAUTOCLAIM"
    )
    recovery_time_ms: float = Field(..., description="Elapsed milliseconds to detect orphan and reclaim ownership")
    pel_cleared: bool = Field(..., description="Flag verifying that pending entries list count returned to zero")
    sla_met: bool = Field(..., description="Whether recovery completed within 30-second target SLA")
    timestamp_iso: str = Field(..., description="Timestamp of recovery completion")
    trace_id: str = Field(..., description="W3C trace context identifier")


class ChaosSystemOverview(BaseModel):
    load_testing_status: str = Field(..., description="Operational status of high-throughput load testing engine")
    connection_pool_status: str = Field(..., description="Operational status of database connection pool")
    redis_memory_status: str = Field(..., description="Operational status of Redis memory and LRU eviction")
    event_loop_status: str = Field(..., description="Operational status of ASGI event loop")
    worker_recovery_status: str = Field(..., description="Operational status of Redis Streams worker recovery")
    resilience_score_pct: float = Field(..., description="Overall resilience score across all chaos domains")
    timestamp_iso: str = Field(..., description="Timestamp of telemetry compilation")
    trace_id: str = Field(..., description="W3C trace context identifier")


# ==================================================
# MASTER REGRESSION AUDIT CONTRACTS (DAY 86)
# ==================================================


class RegressionAssertionDetail(BaseModel):
    assertion_number: int = Field(..., description="Assertion index within suite")
    title: str = Field(..., description="Human-readable assertion title")
    passed: bool = Field(..., description="Whether assertion succeeded")
    details: Optional[str] = Field(default=None, description="Assertion execution telemetry or error description")


class RegressionSuiteReport(BaseModel):
    suite_id: str = Field(..., description="Unique suite identifier")
    suite_name: str = Field(..., description="Display name of the regression suite")
    status: str = Field(default="PASSED", description="PASSED | FAILED")
    assertions_passed: int = Field(..., description="Number of passed assertions")
    total_assertions: int = Field(..., description="Total assertion count")
    duration_ms: float = Field(..., description="Elapsed milliseconds to execute suite")
    assertions: list[RegressionAssertionDetail] = Field(
        default_factory=list, description="List of granular assertion details"
    )


class MasterRegressionReport(BaseModel):
    run_id: str = Field(..., description="Unique regression execution identifier")
    status: str = Field(default="PASSED", description="PASSED | FAILED")
    total_suites: int = Field(..., description="Total audit suites executed")
    suites_passed: int = Field(..., description="Number of suites that passed 100%")
    total_assertions: int = Field(..., description="Total assertions evaluated")
    assertions_passed: int = Field(..., description="Total assertions passed")
    pass_rate_pct: float = Field(..., description="Aggregate assertion pass percentage")
    total_duration_ms: float = Field(..., description="Total elapsed milliseconds for complete regression")
    timestamp_iso: str = Field(..., description="Timestamp of regression execution")
    trace_id: str = Field(..., description="W3C trace context identifier")
    suites: list[RegressionSuiteReport] = Field(default_factory=list, description="Per-suite breakdown reports")


# ==================================================
# ARCHITECTURE BLUEPRINT CONTRACTS (DAY 87)
# ==================================================


class ArchitectureNode(BaseModel):
    id: str = Field(..., description="Unique node identifier")
    name: str = Field(..., description="Display title of the component")
    subsystem: str = Field(..., description="Parent subsystem or architectural tier")
    tech_stack: str = Field(..., description="Technologies and libraries used")
    role: str = Field(..., description="System responsibility")
    protocol: str = Field(..., description="Inbound / outbound communication protocol")
    latency_sla_ms: float = Field(..., description="Expected target latency in milliseconds")


class ArchitectureEdge(BaseModel):
    source: str = Field(..., description="Source node id")
    target: str = Field(..., description="Target node id")
    protocol: str = Field(..., description="Transport protocol: HTTP, WS, REDIS_STREAM, SQL, IPC")
    description: str = Field(..., description="Description of message or payload transfer")
    is_async: bool = Field(default=True, description="Whether transition is asynchronous")


class ArchitectureSubsystem(BaseModel):
    id: str = Field(..., description="Subsystem identifier")
    title: str = Field(..., description="Subsystem display title")
    description: str = Field(..., description="Core architectural tier description")
    nodes: list[ArchitectureNode] = Field(default_factory=list, description="Constituent architecture nodes")


class SystemArchitectureTopology(BaseModel):
    system_name: str = Field(..., description="Application name")
    version: str = Field(..., description="Architecture specification version")
    status: str = Field(default="OPERATIONAL", description="System operational state")
    subsystems: list[ArchitectureSubsystem] = Field(default_factory=list, description="Tiered subsystems")
    edges: list[ArchitectureEdge] = Field(default_factory=list, description="Directed data flow edges")
    mermaid_diagram: str = Field(..., description="Canonical Mermaid syntax string for rendering")
    timestamp_iso: str = Field(..., description="Timestamp of topology generation")
    trace_id: str = Field(..., description="W3C trace context identifier")


# ==================================================
# CODE QUALITY & STATIC ANALYSIS CONTRACTS (DAY 88)
# ==================================================


class CodeQualityCheckItem(BaseModel):
    check_name: str = Field(..., description="Name of the automated quality check")
    tool: str = Field(..., description="Linter or validation engine: ruff | ast | file_scanner")
    status: str = Field(default="PASSED", description="PASSED | WARNING | FAILED")
    issues_found: int = Field(default=0, description="Count of issues detected")
    details: list[str] = Field(default_factory=list, description="Diagnostic details or rule violation messages")
    duration_ms: float = Field(..., description="Elapsed milliseconds for check execution")


class CodeQualityReport(BaseModel):
    run_id: str = Field(..., description="Unique quality scan identifier")
    status: str = Field(default="PASSED", description="PASSED | FAILED")
    total_checks: int = Field(..., description="Number of quality audits executed")
    passed_checks: int = Field(..., description="Number of audits passed")
    total_files_scanned: int = Field(..., description="Total Python source files inspected")
    total_lines_of_code: int = Field(..., description="Aggregate lines of code in app codebase")
    total_issues: int = Field(..., description="Aggregate lint/formatting/quality issues")
    linter_clean: bool = Field(..., description="Whether ruff linter check passes with 0 errors")
    formatter_clean: bool = Field(..., description="Whether ruff formatting check passes")
    checks: list[CodeQualityCheckItem] = Field(default_factory=list, description="Granular check items")
    timestamp_iso: str = Field(..., description="Timestamp of quality scan completion")
    trace_id: str = Field(..., description="W3C trace context identifier")


# ==================================================
# PHASE 2 CAPSTONE CERTIFICATION CONTRACTS (DAY 90)
# ==================================================


class Phase2MilestoneSummary(BaseModel):
    milestone_id: str = Field(..., description="Milestone code: M1 | M2 | M3 | M4 | M5 | CAPSTONE")
    title: str = Field(..., description="Milestone designation")
    status: str = Field(default="SEALED", description="Status: SEALED | CERTIFIED")
    days_covered: str = Field(..., description="Roadmap days range")
    assertions_count: int = Field(..., description="Number of verified audit assertions")
    audit_suite: str = Field(..., description="Associated audit script")
    key_features: list[str] = Field(default_factory=list, description="Core architectural deliverables")


class Phase2CapstoneReport(BaseModel):
    version: str = Field(default="v0.9.0", description="Phase 2 Release Version Tag")
    status: str = Field(default="SEALED", description="Certification Status: SEALED")
    system_name: str = Field(default="Automated Equity Research Engine", description="Application Name")
    total_milestones: int = Field(default=6, description="Total Phase 2 milestones")
    milestones_sealed: int = Field(default=6, description="Number of sealed milestones")
    total_assertions: int = Field(default=48, description="Cumulative audit assertions")
    assertions_passed: int = Field(default=48, description="Cumulative passed assertions")
    pass_rate_pct: float = Field(default=100.0, description="Assertion pass rate percentage")
    stream_health_status: str = Field(default="ACTIVE", description="Redis Streams cluster state")
    circuit_breaker_state: str = Field(default="CLOSED", description="Groq LLM circuit state")
    cache_layer_status: str = Field(default="OPERATIONAL", description="Cache-aside layer state")
    rag_embeddings_status: str = Field(default="OPERATIONAL", description="pgvector RAG state")
    lines_of_code: int = Field(..., description="Total repository Python lines of code")
    python_modules_count: int = Field(..., description="Total Python source files inspected")
    milestones: list[Phase2MilestoneSummary] = Field(
        default_factory=list, description="Constituent milestone summaries"
    )
    timestamp_iso: str = Field(..., description="Timestamp of capstone certification")
    trace_id: str = Field(..., description="W3C trace context identifier")
